### ISSUE TITLE
欢迎老哥回归！更新一下V2P

### ISSUE THREAD

**Issue by Oreomeow** [zero205/JD_tencent_scf#1]
Thanks.

**Comment by zero205** [comment]
这几天比较忙，会尽快抽空更新

**Comment by CACAVOK** [comment]
> Thanks.

哈喽，可以要个联系方式咨询一下V2P怎么使用吗

**Comment by Oreomeow** [comment]
> > Thanks.
> 
> 哈喽，可以要个联系方式咨询一下V2P怎么使用吗

可以，你留个联系方式就行
