### ISSUE TITLE
这两天出现了同步脚本失败问题。之前是正常的。

### ISSUE THREAD

**Issue by YEJT666** [zero205/JD_tencent_scf#10]
![image](https://user-images.githubusercontent.com/79657797/119345018-f08b2a80-bcca-11eb-96dd-e15808b9c3cd.png)

**Comment by YEJT666** [comment]
而且已经试过替换yml

**Comment by zero205** [comment]
应该跟PAT的变量有关系，重新生成一个token试试

**Comment by YEJT666** [comment]
> 应该跟PAT的变量有关系，重新生成一个token试试
已解决，可能是仓库名与PAT名相同导致的。
