### ISSUE TITLE
汪汪乐园 的最大化收益 有问题 建议通过环境变量控制

### ISSUE THREAD

**Issue by sunnyboyi** [zero205/JD_tencent_scf#102]
//最大化硬币收益模式
$.JOY_COIN_MAXIMIZE = '0'
$.log(`最大化收益模式: 已${$.JOY_COIN_MAXIMIZE ? 默认已开启 : `关闭`}  `) 

 这个能否调整下呀   字符串 ‘0’ if 判断 是 true吧   最大化收益   买低级joy 生产的金币 远远不够买的 
等级越高 购买低级joy的成本越高  到后面 2级的joy 每秒生产1  购买需要3W多 ，严重亏损

不反对有人一直认为那个是 最大化收益   能否改进下 这个开关通过环境变量来控制 如  process.env.JOY_COIN_MAXIMIZE 

谢谢！

**Comment by Ca11back** [comment]
感谢,即将修改
