### ISSUE TITLE
动物联萌云函数运行报错

### ISSUE THREAD

**Issue by zeroone012** [zero205/JD_tencent_scf#11]
![171ab202ad5551f7](https://user-images.githubusercontent.com/83265746/119531065-32f34c80-bd49-11eb-9e9e-69de69ca78ba.png)
请问大佬，该如何处理

**Comment by zero205** [comment]
同步lxk大佬更新了，试试还会报错吗？

**Comment by 1727026248** [comment]
同步了，还是报错，我用另一个号重新部署云函数，也是报错🤕

**Comment by 1727026248** [comment]
喔，刚才的更新还没试，😂尴尬了

**Comment by 1727026248** [comment]
![58ccbcf9d847cb2b](https://user-images.githubusercontent.com/83265746/119613727-09770700-bdc3-11eb-957b-bcd45ffd6aa3.jpg)
还是报错🤕🤕

**Comment by zero205** [comment]
我用云函数测试了一下是没问题的，你同步最新的脚本再试试？

**Comment by 1727026248** [comment]
是最新的，我对比了云函数里的代码，是昨天那个最新版，但是一直报错，无法运行🤕

**Comment by 1727026248** [comment]
![Screenshot_2021-05-27-09-30-13-487_com tencent mm](https://user-images.githubusercontent.com/83265746/119751764-63c6a500-be61-11eb-893c-3d99e9841662.jpg)
![Screenshot_2021-05-27-09-30-50-095_com tencent mm](https://user-images.githubusercontent.com/83265746/119751773-675a2c00-be61-11eb-9103-95e90d8b96d4.jpg)
是我没有设置对吗🤕🤕🤕

**Comment by 1727026248** [comment]
🤕🤕大佬，能看看吗

**Comment by 1727026248** [comment]
我试了下单独触发zoo脚本，是可以运行的，但是放在自动部署的里面似乎就会超过900s无法运行

**Comment by Cyj97** [comment]
+1 同样的问题

**Comment by Cyj97** [comment]
健康社区的问题，单独运行也报错。触发器里把健康社区删掉就正常了
