### ISSUE TITLE
惊喜财富岛气球无限报cookie失效

### ISSUE THREAD

**Issue by Hyper-Beast** [zero205/JD_tencent_scf#110]
确定cookie 100%有效，一样的脚本一样的cookie放到docker里跑正常运行。现在我把腾讯云上的云函数都删了新建了一个名字不一样的，把push key改成错误的依然一直收到cookie失效通知，每隔几分钟就会连续收到4条。这个问题是改了京东的密码后出现的
![image](https://user-images.githubusercontent.com/18001712/125657423-b1d9cf00-b52d-4bf0-994f-c8486ebb5c39.png)
![image](https://user-images.githubusercontent.com/18001712/125657431-b2a64c21-26c1-47b6-bbc0-53a69e95aca4.png)
![image](https://user-images.githubusercontent.com/18001712/125657457-e6444186-d2c6-4bb4-89f1-e22bf104e9c2.png)

**Comment by zero205** [comment]
明天问一下腾讯云函数的客服看怎么处理，不然就只能等24小时的最长运行时间自动结束脚本了...

**Comment by Hyper-Beast** [comment]
> 明天问一下腾讯云函数的客服看怎么处理，不然就只能等24小时的最长运行时间自动结束脚本了...

发到昨晚2点多终于消停了，腾讯云还真是不好用

**Comment by JackYin2021** [comment]
> 明天问一下腾讯云函数的客服看怎么处理，不然就只能等24小时的最长运行时间自动结束脚本了...
要不要加个判断 cookie失效 自动中断 昨天删了应用程序都没用

**Comment by zero205** [comment]
我用elecV2P挂也报CK失效了，现在财富岛手动都繁忙，强烈建议不要跑这个脚本
