### ISSUE TITLE
东东农场浇水有问题

### ISSUE THREAD

**Issue by mosquitoes** [zero205/JD_tencent_scf#116]
任务没问题，浇水报错
{"code":"0","totalEnergy":124,"statisticsTimes":null,"totalWaterTimes":12,"sysTime":1626495068026,"finished":false,"message":null,"waterStatus":0,"sendAmount":10,"treeEnergy":2020}

**Comment by zero205** [comment]
我刚抓包看了，这不是报错，是正常浇水返回的结果
