### ISSUE TITLE
关于添加cookies的相关问题

### ISSUE THREAD

**Issue by Iovelollipop** [zero205/JD_tencent_scf#118]
在setting中的secret添加JD_COOKIE时，输入的只有ptkey还是pt_key和pt_pin呢？
如果添加多个，他们之间通过换行还是通过&进行连接呢？
如果我想在原来的基础上添加其他cookie时，update打开后看不到之前添加过的cookie，此时update是添加还是覆盖呢，还需要把之前的cookie重新添加嘛？

**Comment by zero205** [comment]
账号之间的ck格式：pt_key=xxx;pt_pin=xxx;&pt_key=xxx;pt_pin=xxx;
update是覆盖

**Comment by Iovelollipop** [comment]
> 账号之间的ck格式：pt_key=xxx;pt_pin=xxx;&pt_key=xxx;pt_pin=xxx;
> update是覆盖
添加cookie时，遇到了如果cookie中含有—，就自动换行了，请问这个有影响吗？

**Comment by zero205** [comment]
> > 账号之间的ck格式：pt_key=xxx;pt_pin=xxx;&pt_key=xxx;pt_pin=xxx;
> > update是覆盖
> > 添加cookie时，遇到了如果cookie中含有—，就自动换行了，请问这个有影响吗？
没有
