### ISSUE TITLE
jd_joy_reward验证不通过陷入死循环

### ISSUE THREAD

**Issue by nining377** [zero205/JD_tencent_scf#122]
部分log：
🔔宠汪汪兑换二代目, 开始!

====================Hello World====================

====================共12个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/7/19 上午8:00:09=====================

共12个京东账号

3

开始【京东账号1】**********_p

4
start......
342 20京豆 17567
exchange()
JDJRValidator trying......
{"message":"refuse","u":"2","nextVerify":"SLIDE_VERIFY","success":"0"}: 1
{"message":"refuse","u":"2","nextVerify":"SLIDE_VERIFY","success":"0"}: 2
{"message":"fail","nextVerify":"NULL_VERIFY","success":"0"}: 1

……（略）

{"message":"refuse","u":"2","nextVerify":"SLIDE_VERIFY","success":"0"}: 1306
{"message":"refuse","u":"2","nextVerify":"SLIDE_VERIFY","success":"0"}: 1307
{"message":"fail","nextVerify":"NULL_VERIFY","success":"0"}: 535
{"message":"fail","nextVerify":"NULL_VERIFY","success":"0"}: 536

验证跑了上千次，直至容器内存溢出

**Comment by Ca11back** [comment]
已解决
