### ISSUE TITLE
jd_try.js解析报错：getGoodListByCond API返回结果解析出错

### ISSUE THREAD

**Issue by nining377** [zero205/JD_tencent_scf#129]

**Comment by nining377** [comment]
出现错误提示：
加载中...
点击继续加载
啊，内容君离家出走了~

点击刷新重试

初步怀疑是拉取列表的时候请求太快了

**Comment by Ca11back** [comment]
> 出现错误提示：
> 加载中...
> 点击继续加载
> 啊，内容君离家出走了~
> 
> 点击刷新重试
> 
> 初步怀疑是拉取列表的时候请求太快了

感谢反馈,应该是延时问题,已初步尝试修复,个别人还会出现其他借口速度过快,正在测试全局延时

**Comment by Ca11back** [comment]
初步已解决
