### ISSUE TITLE
个别任务都显示未登录

### ISSUE THREAD

**Issue by w1243347117** [zero205/JD_tencent_scf#130]
![image](https://user-images.githubusercontent.com/41610497/126612444-44efafc4-a929-4fb8-b10a-f5841b117f2c.png)
求一份完整的环境变量配置

**Comment by zero205** [comment]
我去看了日志是正常的，确定不是你的ck过期了？

**Comment by w1243347117** [comment]
ck是新拉的

**Comment by w1243347117** [comment]
![image](https://user-images.githubusercontent.com/41610497/126614483-1876807d-b5e2-4b04-bd81-b7415069eb4a.png)
![image](https://user-images.githubusercontent.com/41610497/126614628-d4d26c54-82a2-43ca-a8ef-54c7f7825c0f.png)
是我环境变量问题吗

**Comment by Ca11back** [comment]
请反馈pt_pin参数,建议群内私聊我,pin多少有些敏感
