### ISSUE TITLE
宠汪汪兑换脚本逻辑错误

### ISSUE THREAD

**Issue by xiaoxiyao** [zero205/JD_tencent_scf#140]
开始遍历帐号分别进行验证，只记录了一个validate变量，相当于只验证了一次，导致只有第一个帐号能兑换成功。
应该是在每个帐号兑换前进行验证，或者记录每个帐号的validate。

**Comment by Ca11back** [comment]
确实,我这个都没注意.因为有的时候一个validate能用多个号.....就没发现这一点.如果愿意测试,请群里大吼我要测试joy_reward,会有管理员联系你

**Comment by Ca11back** [comment]
已修复,感谢
