### ISSUE TITLE
哪几个脚本是会将商品加入购物车

### ISSUE THREAD

**Issue by roinlym** [zero205/JD_tencent_scf#141]
哪几个脚本是会将商品加入购物车的？我只搜索到jd_jump.js  jd_small_home.js  jd_bookshop.js这三个里面有加购物车的操作，但是都是默认的不添加购物车的，可以我的账号还是每天都会有新的商品被加入购物车。

**Comment by Ca11back** [comment]
应该是零食街,已修复
