### ISSUE TITLE
这是因为什么？

### ISSUE THREAD

**Issue by yangyangxing** [zero205/JD_tencent_scf#143]
![image](https://user-images.githubusercontent.com/37945726/127439593-a9e4f32d-c8d2-4b79-a0f1-311650967221.png)

**Comment by Ca11back** [comment]
elev2p应该只支持Qx可运行的脚本(也就是不支持require),很多要require的脚本估计都不能运行

**Comment by zero205** [comment]
> elev2p应该只支持Qx可运行的脚本(也就是不支持require),很多要require的脚本估计都不能运行

elecV2P可以用，在脚本开头加// @grant    require
