### ISSUE TITLE
dpqd token

### ISSUE THREAD

**Issue by GaviTate** [zero205/JD_tencent_scf#147]
[出处](https://github.com/shufflewzc/faker2/pull/27/commits/467393f2de5608686903ed0e6824d3fad5480498)

大概有二十多个
  '434DAE741BE9A0490553DAF956FEFE65',//1天，10豆；3天，50豆；10天，100豆；
  '0D9FBEE0928A7010A3A217A08D8E0F55',//7天，100豆；
  'E528907E4FEC60FC75CBFE1BAFA95F8D',//7天，40豆；15天，100豆；30天，100豆;
  '026112EA55A7992C4E89338D994CA812',//7天，30豆；
  '532B4C977CA2066A107C034B9CB3A9DD',//2天，5豆；6天，20豆；8天，50豆；
  '9BABD41E5674FD5791963D5366BEC634',//每日，1豆；5天，10豆；21天，100豆;
  'CE88E5242954E4B97D0B8B387D8B5607',//每日，10积分；5天，50豆；10天，50豆；15天，100豆；20天，50豆，25天，50豆;
  '05A7C949B2AD6AF3B67BB52ACFCA2C01',//每日，5积分；1天，2豆；7天，30豆；
  'EFFD0BF4069A8B6882A55FB07ACDA60F',//每日，10豆；10天，30豆；20天，60豆；30天，100豆；
  '538AE706C42E875C7E187479A5C280F6',//7天，100积分；15天，50豆;
  'FF84F8AE88F0859E57933135955CA69E',//每日，1豆；3天，5豆；7天，10豆；10天，15豆;
  'D7AA93262408C8E203F464475AD1E25B',//7天，5豆；14天，12豆；
  '3F6F1ABCC2D60622F891898018F0A6E2',//每日，1豆；1天，2豆；3天，5豆；7天；10豆；15天，50豆；30天；100豆；
  'B8790B7045C6EE04CC67121D67F3F2C4',//每日，3豆；7天，30豆；
  //'653BEA3B38C505C0DCA41CD9DF0EC910',//每日，2豆；5天，20豆;//店铺耍流氓了;
  '891FA290689133F44E0E8AFCA2A83053',//每日，1积分；8天，9豆；16天，20豆；20天，200积分;
  '46534679506709BBCB1832DE399A969A',//连续7天，10豆；
  '77B06BE4BC3332D9674AD871C7DF5065',//7天，100豆;
  '7B3581A8967257F41B5784DDB82E5123',//3天，100豆；
  'DE73FD2AA5DCA38C3CEF3BD153FB4C24',//每日，10积分；7天，50豆；
  '2215A038745A22795855358B459F32BB',//3天，80-35券、10豆；5天，150-70券、20豆；7天，30豆、199-100券
  '564B04E590F3F04F56A6C8B6C6BBABAC',//7天，25豆;
  'B6ADD43C62C27D2473BF413C5EFE65C9',//3天，20豆；
  '93830BBF47902063E14135B2822BAA0C',//每日5豆；连续7天，10豆；
  '2BC56E3A4912248CBDDFF681D2500A69',//每日，3豆；1天，1豆；2天，2豆；3天，3豆；4天，4豆；
  'DB1997C42F124AAA03DB79BCF5A135AC',//1天，2豆；2天，3豆；3天，5豆；5天，8豆；7天，10豆；
  'AFF456584A2F34F3179C8A0843710911',//3天，10豆；7天，20豆；15天，30豆；30天；50豆；

**Comment by Ca11back** [comment]
感谢,token已经更新过,超过21个意义不大?如果方便,可以直接PR掉已过期的
