### ISSUE TITLE
求邀进TG😭

### ISSUE THREAD

**Issue by wxs-dev** [zero205/JD_tencent_scf#149]
不知道怎么我进不去TG
我TG号是wxsdev
求邀进TG😭😭😭

**Comment by Ca11back** [comment]
请主动加入,你设置的禁止被拉群

**Comment by wxs-dev** [comment]
> 请主动加入,你设置的禁止被拉群

![image](https://user-images.githubusercontent.com/58886165/128192876-64db8bcb-aa84-492c-af1c-52e6f4c1d782.png)
进不去 ，点开显示无法访问此群。我已打开拉群了，求邀😢

**Comment by Air433up** [comment]
同问，我也是这样

**Comment by Air433up** [comment]
我的tg号为速闪，求邀进群组

**Comment by Ca11back** [comment]
> 我的tg号为速闪，求邀进群组

两位我都拉不进去,我有空查一下具体怎么回事

**Comment by zero205** [comment]
你们两个我都解封了，进群记得回答验证问题，不然机器人又会给封了...

**Comment by Air433up** [comment]
> 你们两个我都解封了，进群记得回答验证问题，不然机器人又会给封了...

好的，感谢
