### ISSUE TITLE
关于elecV2P通知格式模板

### ISSUE THREAD

**Issue by zero205** [zero205/JD_tencent_scf#15]
这里仅提供pushplus推送方式模板，其他通知方式根据官方文档以此类推

```bash
{
    "token":"xxxxxx",
    "title":`$title$`,
    "content":`$body$`,
}
```

具体设置如下图所示

![360截图20210529203820194](https://user-images.githubusercontent.com/26343559/120070586-da5fde80-c0bd-11eb-9765-9685efc59b3d.jpg)

**Comment by SalayDay** [comment]
截图这个面板怎么打开   我电脑docker拉取了v2p   然后就不知道接下来怎么操作了

**Comment by zero205** [comment]
docker没用过，看官方的文档。启动elecV2P后，浏览器地址打开:127.0.0.1进入这个控制面板

**Comment by daxinnan** [comment]
想问下通过WSL2 跑的docker-compose，怎么进入这个web界面呢

**Comment by zero205** [comment]
> 想问下通过WSL2 跑的docker-compose，怎么进入这个web界面呢

应该跟上面的docker差不多吧，启动后在浏览器打开控制面板

**Comment by SalayDay** [comment]
[
  {
    "userName": "jd_5bbxxx414",
    "cookie": "pt_key=xxx;pt_pin=jd_5xxx414;"
  },
  {
    "userName": "jd_739xxx89e",
    "cookie": "pt_key=xxx;pt_pin=jd_739xxx89e;"
  },
  {
    "userName": "jd_413xxxe89",
    "cookie": "pt_key=xxx;pt_pin=jd_413xxxe89;"
  }
]


问下   这里的username后面的值随便填吗

**Comment by SalayDay** [comment]
还有就是怎么单独添加个别脚本  和怎么部署tg机器人

**Comment by zero205** [comment]
> [
> {
> "userName": "jd_5bbxxx414",
> "cookie": "pt_key=xxx;pt_pin=jd_5xxx414;"
> },
> {
> "userName": "jd_739xxx89e",
> "cookie": "pt_key=xxx;pt_pin=jd_739xxx89e;"
> },
> {
> "userName": "jd_413xxxe89",
> "cookie": "pt_key=xxx;pt_pin=jd_413xxxe89;"
> }
> ]
> 
> 问下 这里的username后面的值随便填吗

最好就填pt_pin后面的用户名，不能有中文

**Comment by zero205** [comment]
> 还有就是怎么单独添加个别脚本 和怎么部署tg机器人

这些官方文档都有写，建议可以详细看一下

**Comment by SalayDay** [comment]
> > 还有就是怎么单独添加个别脚本 和怎么部署tg机器人
> 
> 这些官方文档都有写，建议可以详细看一下

好的  谢谢大佬

**Comment by SalayDay** [comment]
大佬你好  那些规则啥的弄不

**Comment by fanyh123** [comment]
> > > 还有就是怎么单独添加个别脚本 和怎么部署tg机器人
> > 
> > 
> > 这些官方文档都有写，建议可以详细看一下
> 
> 好的 谢谢大佬

有解决吗?可以分享一下吗

**Comment by ynxu** [comment]
原来的企业微信现在怎么填
