### ISSUE TITLE
京喜财富岛访问过频繁

### ISSUE THREAD

**Issue by mosquitoes** [zero205/JD_tencent_scf#150]
京喜财富岛里面可以的话加个延时，访问过快会触发访问频率限制，接口全部返回【岛上信号有点弱】

**Comment by Ca11back** [comment]
是cfd_loop么,什么环境

**Comment by mosquitoes** [comment]
jd_cfd.js这个，elecV2P上跑的，执行到后面就会
岛上信号有点弱，请稍后再试
游戏能打开，但是接口全部返回这个，感觉是频率限制

**Comment by Ca11back** [comment]
> jd_cfd.js这个，elecV2P上跑的，执行到后面就会
> 岛上信号有点弱，请稍后再试
> 游戏能打开，但是接口全部返回这个，感觉是频率限制

好像别的平台并没有这个现象,您建议在群内先尝试问问其他elec用户吗?
