### ISSUE TITLE
今天更新部署之后就用不了了

### ISSUE THREAD

**Issue by lipwah** [zero205/JD_tencent_scf#156]
用了一个月都很好的，今天更新部署就用不了，请问是哪里出问题了
Error: Cannot find module '/home/runner/work/***_Sign/***_Sign/tencentscf.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error: Process completed with exit code 1.

**Comment by Ca11back** [comment]
云函数ac目前正在尝试无缝升级.私库内会只剩.github一个文件夹.整个过程会自动更新,如有任何问题,请带日志及时反馈!
在更新到第二步的时候可能出现部署失败,不影响,等待全部部署脚本也更新了,就没问题了
理论上不影响青龙用户,如有影响请看最下方反馈
主要新特性:
新部署脚本更稳定,部署失败不会再删除函数,只会停止更新!
自动提醒非私库用户.
减少ac使用时长
每次部署只需要执行'Deploy' action自动拉取最新并部署,'Sync yml repo' action 只是用来同步最新部署脚本,无需像之前一样每次部署要手动同步代码仓库来确保代码最新.目前同步部署脚本还是4小时一次,没有改变,未来会减少同步频率.
云函数失败重试次数设为0,避免无意义多次执行
升级过程:
1.手动或等待自动执行'获取最新脚本'
2,同步后仓库跟以前一样,等待或手动再次执行'获取最新脚本'(名字已经变成了'Sync yml repo')仓库会只剩.github一个文件夹
3.之后再运行的'Deploy' action就是新部署脚本
理论上可以无缝过度,无需手动执行.有感兴趣的话可以尝试手动执行,有错误请及时带完整日志私聊群内@whisper_liu

**Comment by HAHA009** [comment]
哎 readme里写一下。。。 昨天开始整了半天 今天自己重写了sync.yml 把main复制过来 再自己部署
看了这个才想起来看一下主库的部署文件 直接部署主库了。。。微软得给个表彰 节约了好多空间。。。

**Comment by Ca11back** [comment]
> 哎 readme里写一下。。。 昨天开始整了半天 今天自己重写了sync.yml 把main复制过来 再自己部署
> 看了这个才想起来看一下主库的部署文件 直接部署主库了。。。微软得给个表彰 节约了好多空间。。。

确实没有写,反正是无缝过度,部署失败也只是一次.再一个..........你都自己会写action,出问题第一反应不是来主库看看吗...........

**Comment by 2970164793** [comment]
15s › *** › [scf] [scf] Timeout数量达到限制：1800，可提交工单申请提升限制：https://mc.tencent.com/8ios9ANu (reqId: f986a0c6-b6d9-4ef5-862e-47a8c914f587) 
部署失败

**Comment by Ca11back** [comment]
> 15s › *** › [scf] [scf] Timeout数量达到限制：1800，可提交工单申请提升限制：https://mc.tencent.com/8ios9ANu (reqId: f986a0c6-b6d9-4ef5-862e-47a8c914f587)
> 部署失败

群内带日志反馈.别随便找个issue就问,很可能看不到,教程不让手动创建函数(已经划线),按照教程,感谢

**Comment by HAHA009** [comment]
> 
> 
> > 哎 readme里写一下。。。 昨天开始整了半天 今天自己重写了sync.yml 把main复制过来 再自己部署
> > 看了这个才想起来看一下主库的部署文件 直接部署主库了。。。微软得给个表彰 节约了好多空间。。。
> 
> 确实应该写,现在加了一下,抱歉.当初想着反正是无缝过度,部署失败也只是一次.再一个..........您都自己会写action,出问题第一反应不是来主库或者群内看看吗...........部署也有日志,看一下就知道成功没.....咋还自己写上了....

TG不太能用 公司电脑。。。 看了一眼主库 和 scf 想着是不是你们写反了 main转私库scf 然后私库main是空的 规避风险，很多人用这招 先入为主了。。。
