### ISSUE TITLE
自己仓库只剩下一个文件夹了

### ISSUE THREAD

**Issue by Iovelollipop** [zero205/JD_tencent_scf#159]
很久之前克隆的，现在仓库只剩下文件夹了，云函数的脚本还在正常运行，我需要更新，或者换仓库嘛？或者说我不用做任何操作

> 
![370%3O9B4 )YC_1$3@3U R0](https://user-images.githubusercontent.com/77190737/129251218-13c67e94-c23e-4561-8b19-53619f5bcaf6.png)
![P`F%8 ~TR{QBSON JL {D2U](https://user-images.githubusercontent.com/77190737/129251292-1e7210f1-b712-481c-9b3e-8398fc1ade8c.png)

**Comment by 3136083906** [comment]
me too

**Comment by Ca11back** [comment]
> me too

请看置顶issue #156
