### ISSUE TITLE
金机奖投票通知这么多undefined，哪里的问题？

### ISSUE THREAD

**Issue by greenwave1987** [zero205/JD_tencent_scf#160]
![129105690-3e105176-ada2-4fab-b168-c70335ac6a49](https://user-images.githubusercontent.com/48582745/129301594-316ae59e-44b6-40af-8ff9-ccc9fff99df0.jpg)

**Comment by 791533790** [comment]
我也想问。  而且没有找到那个金机馆。  楼上有找到么

**Comment by Ca11back** [comment]
已经更新入口描述,请重新查看脚本开头

**Comment by HAHA009** [comment]
所以最后拿了啥实物。。。

**Comment by 791533790** [comment]
> 所以最后拿了啥实物。。。

没找到。 不知道是不是过期了

**Comment by Ca11back** [comment]
> > 所以最后拿了啥实物。。。
> 
> 没找到。 不知道是不是过期了

大概率提示出错,脚本已经更新,请检查问题是否修复.

**Comment by greenwave1987** [comment]
更新后通知还是老样子。
