### ISSUE TITLE
金机奖投票还是出错，能否增加变量关闭这个通知，或关闭这个脚本？执行日志更长，提示出错。

### ISSUE THREAD

**Issue by greenwave1987** [zero205/JD_tencent_scf#162]
![image](https://user-images.githubusercontent.com/48582745/129430166-de231528-9de8-43c5-82bb-97b8a8afe281.png)

**Comment by Ca11back** [comment]
十分抱歉,后续尝试修复.SCF有NOT_RUN变量可以设置,语法与触发器参数一致.具体内容可到群内查看历史置顶
