### ISSUE TITLE
部署时报错，超过timeout限制

### ISSUE THREAD

**Issue by WaterChen520** [zero205/JD_tencent_scf#166]
具体报错如下图：
[![f6C9wd.png](https://z3.ax1x.com/2021/08/14/f6C9wd.png)](https://imgtu.com/i/f6C9wd)
[![f6CCTA.png](https://z3.ax1x.com/2021/08/14/f6CCTA.png)](https://imgtu.com/i/f6CCTA)

**Comment by Ca11back** [comment]
https://github.com/zero205/JD_tencent_scf/issues/156#issuecomment-898858891
