### ISSUE TITLE
京喜牧场无法给小鸡喂菜了

### ISSUE THREAD

**Issue by nining377** [zero205/JD_tencent_scf#169]
日志：
共有白菜8964颗，每次喂10颗，可以喂896次
开始第1次喂白菜
投喂失败，活动ID不正确
{"data":null,"message":"活动ID不正确","ret":1021}

**Comment by Ca11back** [comment]
j脚本大概率非最新,请确认版本.

**Comment by HAHA009** [comment]
这个鸡每天吃菜的量是有上限的 你手动喂他也不吃 就不是脚本的问题了
由于金币刷太猛 绝对吃不完买的白菜 最后总要溢出的。。。

**Comment by nining377** [comment]
> j脚本大概率非最新,请确认版本.

感谢大佬回复，已经排查完毕，是我自身原因，手动跑了才发现环境里有同名文件，没有复制进去
