### ISSUE TITLE
sendNotify.js tg代理无法使用

### ISSUE THREAD

**Issue by 520xcy** [zero205/JD_tencent_scf#170]
未声明TG_PROXY_HOST与TG_PROXY_PORT

**Comment by Ca11back** [comment]
请详细阐述,没有明白

**Comment by 520xcy** [comment]
使用电报机器人通过代理服务器发送通知的时候需要配置代理端口和代理服务器地址。
`if (process.env.TG_PROXY_HOST && process.env.TG_PROXY_PORT) {
        const tunnel = require("tunnel");
        const agent = {
          https: tunnel.httpsOverHttp({
            proxy: {
              host: process.env.TG_PROXY_HOST,
              port: process.env.TG_PROXY_PORT * 1
            }
          })
        }`
在文件320行有对tg代理服务器变量和端口做判断，存在变量则使用代理，但在29行只有机器人的token和userid配置。没有关于代理服务器和端口的设置。

**Comment by Ca11back** [comment]
> 使用电报机器人通过代理服务器发送通知的时候需要配置代理端口和代理服务器地址。
> `if (process.env.TG_PROXY_HOST && process.env.TG_PROXY_PORT) { const tunnel = require("tunnel"); const agent = { https: tunnel.httpsOverHttp({ proxy: { host: process.env.TG_PROXY_HOST, port: process.env.TG_PROXY_PORT * 1 } }) }`
> 在文件320行有对tg代理服务器变量和端口做判断，存在变量则使用代理，但在29行只有机器人的token和userid配置。没有关于代理服务器和端口的设置。

我没有十分理解一个能看懂代码的人提这种问题..........
以至与我十分怀疑自己的理解的对不对........
您是在问环境变量为什么没有在开头声明么?????
环境变量.....之所以叫环境变量..........因为他是环境变量..............

**Comment by 520xcy** [comment]
是希望您方便的话可以在下个版本更新时候在声明部分像token一样加一下和代理服务器和端口的填写位置，方便不懂代码的朋友使用

**Comment by Ca11back** [comment]
> 是希望您方便的话可以在下个版本更新时候在声明部分像token一样加一下和代理服务器和端口的填写位置，方便不懂代码的朋友使用

大部分老旧变量都可以阅读库内githubaction.md. 教程不是很完善(一个真就是能用就行,第二个就是很多都是有,但是要自己找.第三个就是个人认为有一点门槛,也算是好事情.),如果您有能力完善教程,欢迎PR.
