### ISSUE TITLE
另一种获取Cookie的方法(Application)双端可用

### ISSUE THREAD

**Issue by hshx123** [zero205/JD_tencent_scf#178]
## 1.PC端
1. 打开 [京东手机版页面](https://m.jd.com/) 并使用手机验证码登陆(这种方式Cookie有效期最长，约31天)

2. 按 `F12` 打开开发者工具，选择 `Application`
![](https://gitee.com/hshx123/picplus/raw/master/20210819102356165.png)

## 2.安卓端

1. 安装kiwi浏览器(或有开发者工具的浏览器都可以) [查看链接](https://66ccff.work/other/kiwi.html)

2. 打开 [京东手机版页面](https://m.jd.com/) 并使用手机验证码登陆(这种方式Cookie有效期最长，约31天)

2. 打开开发者工具(菜单栏里)，打开电脑模式，选择 `Application`

3. 找到pk_key和pt_pin

- ①如果可以打开 **小窗** ，尝试长按文字后拖入某些可以打字的窗口［如系统自带的笔记/标签，QQ(会自动发送)］

![Gif](https://cdn.jsdelivr.net/gh/hshx123/cdn@master/2021/08/20/20210820185803190.gif)

- ②截图，用某些软件文字识别(比如翻译软件、QQ等)
![](https://gitee.com/hshx123/picplus/raw/master/20210820132845750.jpg)

**Comment by Ca11back** [comment]
感谢,这不是您写吧,是否可以提供源地址,我转载一个过来.

**Comment by hshx123** [comment]
> 谢谢，这不是您写的吧，是否可以提供源地址，我转载一个过来。

确实是我写的ヽ(〃∀〃)ﾉ，但是之前用的另外一个人的库，有点旧了，我正在改教程

https://66ccff.work/teach/jd.html

另外，我的TG @hshx123 ，Github不太常看

**Comment by Ca11back** [comment]
> > 谢谢，这不是您写的吧，是否可以提供源地址，我转载一个过来。
> 
> 确实是我写的ヽ(〃∀〃)ﾉ，但是之前用的另外一个人的库，有点旧了，我正在改教程，改完在转吧(๑°⌓°๑)
> 
> https://66ccff.work/teach/jd.html
> 
> 另外，我的TG @hshx123 ，Github不太常看

感谢大佬,如果改完的话,有兴趣可以直接PR
