### ISSUE TITLE
水果masterHelpShare()  和 萌宠 slaveHelp() 调用的位置不能放在后面

### ISSUE THREAD

**Issue by lovelyelfpop** [zero205/JD_tencent_scf#179]
本来原始的脚本 masterHelpShare() 放在 jdFruit() 里的，
第一个账号助力时会助力 shareCodes[0]
第二个账号助力时会助力 shareCodes[1]

作者您仓库的脚本 masterHelpShare 放在了所有账号做完任务后，
导致每个账号都去助力 shareCodes[shareCodes.length - 1]

萌宠同理

**Comment by Ca11back** [comment]
十分感谢,owner到时候处理一下

**Comment by zero205** [comment]
@lovelyelfpop **已修复，感谢提醒**
