### ISSUE TITLE
腾讯云产生20多块钱的费用

### ISSUE THREAD

**Issue by Hyper-Beast** [zero205/JD_tencent_scf#181]
之前每个月免费送的够抵扣了，前两天提示欠费充了20块，结果才两天又提示欠费了，腾讯云的方法不好用了吗？
ps:我10个号在跑

**Comment by HAHA009** [comment]
没遇到 你看看支出明细不就清楚了 来这里问 谁等解答

**Comment by Ca11back** [comment]
.除了扣费什么都不知道=脚本不好使,就是不好使.

**Comment by simple-png** [comment]
关了京东试用脚本就行了，这个占资源大头
