### ISSUE TITLE
请问谁能告诉我部署文件方式部署怎么弄啊

### ISSUE THREAD

**Issue by 3136083906** [zero205/JD_tencent_scf#188]
在.env文件里添了云函数密钥，部署成功了，但是函数里没cookie啊

**Comment by Ca11back** [comment]
请看群内置顶有简易教程,部署文件方式暂不提供技术支持,仅限有能力用户使用
环境变量请填入config.yml

**Comment by aefa6** [comment]
加群没看到有置顶呀 是我玩不来么

**Comment by Ca11back** [comment]
> 加群没看到有置顶呀 是我玩不来么

现在去仓库scf2分支readme也有简易说明了.
