### ISSUE TITLE
jd_bean_sign.js有些ck已经//，但依旧收到推送，能否过滤掉

### ISSUE THREAD

**Issue by ITdesk01** [zero205/JD_tencent_scf#189]
举个例子
jdCookie.js
里面

'pt_key=xxxx;pt_pin=1;',
'pt_key=xxxx;pt_pin=2;',
'pt_key=xxxx;pt_pin=3;,
'pt_key=xxxx;pt_pin=4;',

这样子运行jd_bean_sign.js就会收到四个推送

但我这边有几个号我用//禁用了，但依旧推送，这个有点烦

'pt_key=xxxx;pt_pin=1;',
'pt_key=xxxx;pt_pin=2;',
//'pt_key=xxxx;pt_pin=3;,
//'pt_key=xxxx;pt_pin=4;',

按照以前的签到, //的这pin3 pin4就应该不推送了，但我依旧收到他们的推送，请修复这个问题，感谢

**Comment by Ca11back** [comment]
请删除cookieset.json, 是nobyda上游缓存文件,未来有空会尝试更改阻止其写入,如果我有空且还记得的话........
