### ISSUE TITLE
每次自动部署就清空了腾讯云配置的cookie，这个怎么办

### ISSUE THREAD

**Issue by tangclQaQ** [zero205/JD_tencent_scf#19]
每次自动部署后就清空了腾讯云里的cookie，这个怎么能让他不清空

**Comment by zero205** [comment]
把京东cookie添加到仓库变量secret即可，变量名称JD_COOKIE

**Comment by iostraema3213** [comment]
![111](https://user-images.githubusercontent.com/46365772/120877577-e8e05580-c5e9-11eb-9c21-82f4688cd2b2.png)
仓库变量加JD_COOKIE了，但是我每次部署去腾讯云看日志，cookie都获取不到，我只能在腾讯云那边手动再加下环境变量才行。这是为什么。难道是我fork的原因吗

**Comment by zero205** [comment]
跟fork没关系，你这不是直接在左栏Secrets添加的变量？

**Comment by iostraema3213** [comment]
添加变量这步文档里没具体写，我不太清楚，为了保险，我都弄了，左栏Serets也设置了
