### ISSUE TITLE
关于jd_try.js失效的一些看法与解决思路

### ISSUE THREAD

**Issue by nining377** [zero205/JD_tencent_scf#192]
jd_try.js的失效是由于获取试用商品列表的接口更改了，不再使用try.m.jd.com域名，请求方式也随之变更，目前请求方式为https://api.m.jd.com/client.action?appid=newtry&functionId=try_feedsList&uuid=1356330333333663-4693733633568346&clientVersion=10.1.2&client=wh5&osVersion=10&area=20_1761_1766_25412&networkType=wifi&body=%7B%22geo%22%3A%7B%22lng%22%3A%22108.282406%22%2C%22lat%22%3A%2222.833458%22%7D%2C%22tabId%22%3A%222%22%2C%22page%22%3A1%2C%22previewTime%22%3A%22%22%7D
直接请求会提示跨域，可能需要在headers里添加一些东西，关键点在于body里面的tabId与page，tabId1为精选，2为闪电试，与[京东试用首页](https://prodev.m.jd.com/mall/active/G7sQ92vWSBsTHzk4e953qUGWQJ4/index.html)的排序保持一致，只要能正确获取列表，剩下的逻辑应该是保持不变的，由于不会写js，希望大佬能修复该脚本

**Comment by Ca11back** [comment]
非常感谢您的建议
个人最近太忙,如果有可能会群内其他大佬可能会修复.

**Comment by X1a0He** [comment]
已修复
https://github.com/zero205/JD_tencent_scf/pull/193

**Comment by RainCat2** [comment]
> 已修复
> #193

感谢大佬的付出

**Comment by nining377** [comment]
> 已修复
> #193

感谢大佬的付出
