### ISSUE TITLE
jd_bean_change是否可以添加环境变量简化通知

### ISSUE THREAD

**Issue by wrong5210** [zero205/JD_tencent_scf#194]
通知过长导致bark发送消息失败

**Comment by Ca11back** [comment]
可否提供简化例子? 目前的好像并不长?

**Comment by wrong5210** [comment]
> 可否提供简化例子? 目前的好像并不长?

目前通知样式

京东资产变动

👇=========账号1=========👇
账号名称：jd_1
今日收入：252京豆 🐶
昨日收入：101京豆 🐶
昨日支出：0京豆 🐶
当前京豆：5644(今日将过期0)京豆🐶
京喜牧场：212枚鸡蛋
极速金币：1261229金币(≈126.12元)
京东赚赚：174700金币(≈17.47元)
领现金  ：8.38元
东东农场：500ML卸妆水,进度:72.83%(10天)
京喜工厂：沃尔玛10元电子卡,进度:19.89%(6天)
东东萌宠：2只装 大号收纳袋,进度:31.8%(3/4块)
🧧🧧🧧🧧红包明细🧧🧧🧧🧧
当前总红包：2.77(今日总过期0.89)元 
京喜红包：2.34(今日将过期0.57)元 
极速红包：0.00(今日将过期0.00)元 
京东红包：0.43(今日将过期0.32)元 
健康红包：0.00(今日将过期0.00)元 

👇=========账号2=========👇
账号名称：jd_2
今日收入：220京豆 🐶
昨日收入：111京豆 🐶
昨日支出：0京豆 🐶
当前京豆：658(今日将过期0)京豆🐶
极速金币：1055746金币(≈105.57元)
京东赚赚：154900金币(≈15.49元)
领现金  ：7.1元
东东农场：4L金龙鱼调和油,进度:52.91%(54天)
东东萌宠：3层抽纸巾30包,进度:0%(0/4块)
🧧🧧🧧🧧红包明细🧧🧧🧧🧧
当前总红包：4.22(今日总过期0.59)元 
京喜红包：3.82(今日将过期0.30)元 
极速红包：0.06(今日将过期0.06)元 
京东红包：0.34(今日将过期0.23)元 
健康红包：0.00(今日将过期0.00)元 



助力池提交方法请加入TG群组：
https://t.me/jd_zero_205

单个账号不长，多账号就有点超字数了
是否可以改成之前的通知样式或者每个账号分别通知？

附之前通知样式参考

账号2：jd
昨日收入：109京豆 🐶
昨日支出：0京豆 🐶
当前京豆：0京豆 🐶
当前红包：0.58元🧧
今日将过期：0.07元红包🧧如发现新活动脚本

**Comment by EchoChan314** [comment]
process.env.BEANCHANGE_PERSENT 
这个参数本身就可以让通知分段。

**Comment by wrong5210** [comment]
> process.env.BEANCHANGE_PERSENT
> 这个参数本身就可以让通知分段。

不好意思我在githubaction.md没找到这个环境变量，请问怎么设置？

**Comment by Ca11back** [comment]
> process.env.BEANCHANGE_PERSENT
> 这个参数本身就可以让通知分段。

我看成bean_sign了.......这两天睡得少人有点傻.
感谢大佬解答.

**Comment by Ca11back** [comment]
> > process.env.BEANCHANGE_PERSENT
> > 这个参数本身就可以让通知分段。
> 
> 不好意思我在githubaction.md没找到这个环境变量，请问怎么设置？

填写数字代表分几段,,请简略阅读脚本.方便请PR githubaction.md感谢.
