### ISSUE TITLE
求助下汪汪乐园的问题

### ISSUE THREAD

**Issue by fantasyjqc001** [zero205/JD_tencent_scf#197]
大佬们，有没有可以直接开新阶段的脚本呀，我的极速版app的汪汪乐园进去一直转圈没法操作，现在已经满级了，脚本还在买26级的狗子。。。不会开启新阶段。。。

**Comment by zero205** [comment]
> 大佬们，有没有可以直接开新阶段的脚本呀，我的极速版app的汪汪乐园进去一直转圈没法操作，现在已经满级了，脚本还在买26级的狗子。。。不会开启新阶段。。。

一直转圈？是新手引导任务没过吗？

**Comment by fantasyjqc001** [comment]
> > 大佬们，有没有可以直接开新阶段的脚本呀，我的极速版app的汪汪乐园进去一直转圈没法操作，现在已经满级了，脚本还在买26级的狗子。。。不会开启新阶段。。。
> 
> 一直转圈？是新手引导任务没过吗？

应该不是，是根本进不去，就是页面一片空白中间一个圈圈在转。。。然后用脚本是可以跑任务/助力/合成啥的。。。不知道什么情况

**Comment by Ca11back** [comment]
新手任务过了么?
