### ISSUE TITLE
领券中心是不是有问题

### ISSUE THREAD

**Issue by 3136083906** [zero205/JD_tencent_scf#20]
不自动签到，有的任务能完成有的任务不能点点券好像失效了。

**Comment by zero205** [comment]
是的，等lxk大佬修复吧

**Comment by 3136083906** [comment]
> 是的，等lxk大佬修复吧

我脚本拷贝过来了，也部署成功了，之后再跑同步最新脚本脚本也跑成功了，但是没拷贝过来。日期还是我第一次拷贝的时候的日期。
