### ISSUE TITLE
京喜工厂运行完成后不能结束进程，一直挂在后台

### ISSUE THREAD

**Issue by VergLsm** [zero205/JD_tencent_scf#201]

**Comment by Ca11back** [comment]
云函数是么

**Comment by VergLsm** [comment]
不是，自己搭建的docker，从lxk时代一直到现在了，其它脚本都能正常运行，前几天pull之后工厂的脚本就不能正常退出，我观察到有些时候也能正常退出，不明原因。

**Comment by Ca11back** [comment]
确定是仓库脚本么,能否提供完整日志

**Comment by Ca11back** [comment]
觉得不方便可以进群私聊@whisper_liu,私发日志文件

**Comment by Ca11back** [comment]
已解决,$.done后process.exit()函数
