### ISSUE TITLE
diy文件夹下的serverless.yml如何与主库中的serverless.yml保持同步

### ISSUE THREAD

**Issue by zhuiyue132** [zero205/JD_tencent_scf#206]
如题。

或者：如何额外的设置一个diy的定时任务，必须使用 serverless.yml 去覆盖么 ？

我尝试了在腾讯云后台手动设置定时任务后，再次部署后会把手动设置的定时任务删除，所以此路不通。

**Comment by Ca11back** [comment]
高级需求面向高级用户,你自己追加一个触发器进去也行啊.
不过建议还是还是直接用实验性特性.
