### ISSUE TITLE
外网出流量巨高

### ISSUE THREAD

**Issue by giterfor126** [zero205/JD_tencent_scf#207]
1点左右时候外网出流量，钱跑的比较多，但是那个时候也没有执行，是什么情况

**Comment by giterfor126** [comment]
有遇到的吗

**Comment by Ca11back** [comment]
> 有遇到的吗

你把issue自己关了还问有没有遇到的

**Comment by Ca11back** [comment]
云函数如果有流量异常高的,愿意尝试弄清问题的,看反馈流程/群内'云函数扣费'关键词后私聊@whisper_liu.协助解决.(需要你有一点点基础)

**Comment by zhanggaolei001** [comment]
我试过签到的那个脚本,就是jd_bean_sign.js里面调用的那个,能把带宽吃满(上传下载都很夸张),但是时间不知道跟你的对不对得上.原因不知道,我太菜,定位不到原因,希望能给各位大佬一点线索.

**Comment by giterfor126** [comment]
> > 有遇到的吗
> 
> 你把issue自己关了还问有没有遇到的

哈哈哈哈我看大家都关了 我还以为得关闭才行
