### ISSUE TITLE
使用配置文件部署时遇到的问题

### ISSUE THREAD

**Issue by jkluio78** [zero205/JD_tencent_scf#209]
**1.按照方式二和教程**
![image](https://user-images.githubusercontent.com/74967641/134864259-a9ef8bcf-6833-4d3b-9e78-d2d68660987c.png)

**2.建立私有库，import `https://github.com/Ca11back/doge-template`**
![image](https://user-images.githubusercontent.com/74967641/134864295-13eedbf8-408e-4703-bc98-81c36ed142be.png)

**3.但是私库只有一个传统部署方法的action，我看代码不是有2个yml文件吗？配置文件部署的action怎么没看到？**
![image](https://user-images.githubusercontent.com/74967641/134865319-efcf0515-bf71-45bd-b862-cf20c15317af.png)
![image](https://user-images.githubusercontent.com/74967641/134865055-be7701e9-93e1-436a-b440-a5b1febfab12.png)

**Comment by Ca11back** [comment]
![image](https://user-images.githubusercontent.com/24651341/134866992-2b7e7bd9-05ea-4501-a657-37eb7ce50a32.png)
emmm,刷新一下?你去那个库看一眼也是两个action,怎么会变成一个

**Comment by jkluio78** [comment]
可能是我账号的问题，在部署文件部署的yml文件加了个空格再提交就有action了
