### ISSUE TITLE
elecv2p里添加环境变量的方式

### ISSUE THREAD

**Issue by daxinnan** [zero205/JD_tencent_scf#21]
是像填账号Cookie一样写在JSMANAGE那里吗？包括各种互助码

![image](https://user-images.githubusercontent.com/26436171/121194639-831df300-c8a1-11eb-9061-12f5ac622895.png)

像图里我这样写对吗老哥，然后像`JOY_RUN_FLAG`这样的值的`TYPE`是不是要改成`boolean`？麻烦老哥有空回答下，谢谢啦

**Comment by zero205** [comment]
应该是string，自己测试一下，我主要是用的云函数

**Comment by CACAVOK** [comment]
放弃了，改用云函数了

**Comment by SalayDay** [comment]
> 应该是string，自己测试一下，我主要是用的云函数

大佬能v2p能出一个添加多个自定义通知的教程吗
