### ISSUE TITLE
部署升级云函数问题

### ISSUE THREAD

**Issue by a1564471347** [zero205/JD_tencent_scf#211]
![Uploading EC1054D3-8F93-4283-9A0E-1A2FA133FEBD.jpeg…]()

**Comment by a1564471347** [comment]
![Uploading 59495495-CE05-47DA-8D4D-9D5C692E6C23.jpeg…]()

**Comment by Ca11back** [comment]
图没有传上来.
配置文件部署仅建议有一点点基础的朋友升级,因为目前没有特别详细的那种教程,

**Comment by a1564471347** [comment]
![Uploading 3D040EB3-5C36-4A61-8A89-F26C1B7B7484.jpeg…]()

**Comment by Ca11back** [comment]
> Uploading 3D040EB3-5C36-4A61-8A89-F26C1B7B7484.jpeg…

............你自己能看见图么
