### ISSUE TITLE
实验性特性

### ISSUE THREAD

**Issue by zhuiyue132** [zero205/JD_tencent_scf#214]
看了一眼config.json ，有个疑问：只能设置整点运行吗？
value 为数组或数字。

**Comment by Ca11back** [comment]
实验性特性请在对应仓库开issue.
设计的就是整点触发机制.

**Comment by Ca11back** [comment]
如果感兴趣,可以入群探讨更多,还想开issue的话麻烦移步到对应仓库,当时没有做精准cron就是因为小时触发已经可以解决问题,那种精准触发就被废弃了.
如果大佬有高见,可以入群探讨.
