### ISSUE TITLE
分享一个获取jd浏览器ck的插件 

### ISSUE THREAD

**Issue by jinwyp** [zero205/JD_tencent_scf#221]
https://github.com/jinwyp/tgfcerblock#get-cookie-chrome-extensions

可以放到readme 里面 
https://github.com/zero205/JD_tencent_scf/blob/main/backUp/GetJdCookie2.md

**Comment by an0na** [comment]
> 感谢贡献,您方便的话可以PR一下吗,这个教程其实也很少用了

我提交了PR，麻烦MR一下。

**Comment by Ca11back** [comment]
> > 感谢贡献,您方便的话可以PR一下吗,这个教程其实也很少用了
> 
> 我提交了PR，麻烦MR一下。

感谢
