### ISSUE TITLE
财富岛的任务赚金币 浏览任务没有自动运行

### ISSUE THREAD

**Issue by dark748001** [zero205/JD_tencent_scf#227]
浏览5秒那几个任务不做 逛逛当地好货 邀请有礼 免费领菜 签到领钱 超值好货
![Screenshot_2021-10-16-15-20-33-03_18c92e8c2d5e39d](https://user-images.githubusercontent.com/64937100/137577980-267b6a88-4f19-45c6-898f-68616d7b77bf.jpg)

**Comment by Ca11back** [comment]
你咋得了这是,反馈流程咋写的啊,日志呢........
