### ISSUE TITLE
大佬好像惊喜牧场的内部助力红包失效了

### ISSUE THREAD

**Issue by fantasyjqc001** [zero205/JD_tencent_scf#249]
大佬好像惊喜牧场的内部助力红包失效了，脚本跑的时候显示助力XXX，但是回到牧场看没有助力。

另外求问大佬，如果账号出现这种，是不是就废了。。。app那边进不去牧场，但是脚本可以跑

![image](https://user-images.githubusercontent.com/87258635/139517689-df3361a0-b291-4744-854f-68cf460835df.png)

**Comment by Ca11back** [comment]
群内反馈....完整日志
