### ISSUE TITLE
青龙面板中脚本更新问题

### ISSUE THREAD

**Issue by wangyuan0217** [zero205/JD_tencent_scf#251]
未fork到自己仓库，直接 ql repo 该库到青龙面板，   之后该仓库脚本更新后面板中的脚本怎么同步更新啊。是要手动在ql repo一次吗

**Comment by Cococloud** [comment]
自己在青龙自动任务中手动添加，按需要设定好运行时间。

**Comment by Ca11back** [comment]
> 自己在青龙自动任务中手动添加，按需要设定好运行时间。

感谢大佬解答
