### ISSUE TITLE
task zero205_JD_tencent_scf_main_jd_unsubscribe.js 问题

### ISSUE THREAD

**Issue by T3rdW** [zero205/JD_tencent_scf#262]
![image](https://user-images.githubusercontent.com/14792476/140616783-ce6ee5a3-4d39-4f07-bd4a-3749481a7c14.png)
感觉应该不是判断字符长度问题,导致了无限判断,运行时间过长
![image](https://user-images.githubusercontent.com/14792476/140616806-7acae759-4dea-43e6-a1e9-0b2b6b6c3287.png)

**Comment by Ca11back** [comment]
应该是list里面莫名其妙推了个不存在的0进去吧,感兴趣调试一下?

**Comment by T3rdW** [comment]
出现这个问题的账号不是我的,没法调试.应该是碰到了什么特殊原因,并不是每个账号都这样.

**Comment by Ca11back** [comment]
感兴趣可以按我说的调一下

> 出现这个问题的账号不是我的,没法调试.应该是碰到了什么特殊原因,并不是每个账号都这样.

**Comment by Ca11back** [comment]
同步更新了简单跳出
