### ISSUE TITLE
关于京喜牧场没有鸡但是有合成卡的时候脚本不执行的问题

### ISSUE THREAD

**Issue by nining377** [zero205/JD_tencent_scf#264]
jd_jxmc.js脚本中，逻辑少许错误，当账号内合成卡够孵化小鸡但是牧场里面没有鸡的时候会被跳过执行，实测把290行await buyChick(configInfo,homePageInfo,cardInfo);提前执行合成小鸡后脚本可以正常运行

**Comment by Ca11back** [comment]
没看见issue,感谢,明天有空我确认一下

**Comment by Ca11back** [comment]
0fe65c6
感谢,已经修正

**Comment by nining377** [comment]
> [0fe65c6](https://github.com/zero205/JD_tencent_scf/commit/0fe65c68a77ed28c210821a21753f12b40519a57) 感谢,已经修正

大佬辛苦了
