### ISSUE TITLE
极速版签到报错

### ISSUE THREAD

**Issue by KyonCN** [zero205/JD_tencent_scf#265]
> ******开始【京东账号1】xxxx*********
> 
> 【幸运大转盘】剩余抽奖机会：0
> 【幸运大转盘】剩余抽奖机会：0
> 
> 京东账号1开始助力【zero205】邀请有礼，感谢！
> 
> 
> ❗️京东极速版, 错误!
> TypeError: data.data is not iterable
>     at /ql/scripts/zero205_JD_tencent_scf_main_jd_speed_sign.js:301:37
>     at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/zero205_JD_tencent_scf_main_jd_speed_sign.js:928:5721)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 
> ❗️京东极速版, 错误!
> TypeError: Cannot read property 'taskBubbles' of undefined
>     at /ql/scripts/zero205_JD_tencent_scf_main_jd_speed_sign.js:372:29
>     at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/zero205_JD_tencent_scf_main_jd_speed_sign.js:928:5721)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 
> ❗️京东极速版, 错误!
> TypeError: Cannot read property 'goldBalance' of undefined
>     at /ql/scripts/zero205_JD_tencent_scf_main_jd_speed_sign.js:584:35
>     at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/zero205_JD_tencent_scf_main_jd_speed_sign.js:928:5721)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 非月底,不自动领下单红包奖励
> 
> 🔔京东极速版, 结束! 🕛 3.201 秒
> 

已经报错两天，是账号被风控了还是京东改版了

**Comment by Ca11back** [comment]
参照ccwav增加了跳过,如果报错尝试换ip执行
