### ISSUE TITLE
想请问下，这个部署到云函数后，还需要自己定义自动执行的时间吗？是否有每个脚本执行的参考时间哈？

### ISSUE THREAD

**Issue by lendcc** [zero205/JD_tencent_scf#27]

**Comment by zero205** [comment]
不需要另外设置，已经设定了每个脚本的运行时间。如果需要修改触发时间的话也可以自己修改触发器

**Comment by lendcc** [comment]
> 
> 
> 不需要另外设置，已经设定了每个脚本的运行时间。如果需要修改触发时间的话也可以自己修改触发器

哦哦好的，谢谢您

**Comment by lendcc** [comment]
> 
> 
> 不需要另外设置，已经设定了每个脚本的运行时间。如果需要修改触发时间的话也可以自己修改触发器

抱歉再打扰您。 您说的那个腾讯云的环境变量跟github里的环境变量需保持一致，是包括Github上需要填的 PAT,以及各种京东助力码，推送等之类的环境变量都要在腾讯云里的环境变量添加上去吗？

**Comment by GYJ09** [comment]
大佬怎么部署啊，按教程部署完没有任何效果啊
