### ISSUE TITLE
jd_bean_sign.js签到提示cookie异常

### ISSUE THREAD

**Issue by sgzman** [zero205/JD_tencent_scf#272]
![Snipaste_2021-11-18_10-29-03](https://user-images.githubusercontent.com/31655098/142340582-aa65b272-9840-4d76-9afd-76afa5f313b0.png)

其余的脚本使用此cookie的时候是正常的。

**Comment by Ca11back** [comment]
补个分号

**Comment by sgzman** [comment]
> 补个分号

感谢，我找了好久的问题。就是没想到是分号的问题。
