### ISSUE TITLE
求大神帮忙看看点击run workflow出现错误

### ISSUE THREAD

**Issue by pengpengdaye** [zero205/JD_tencent_scf#273]
/usr/bin/docker run --name ghcrioreposyncgithubsyncv230_6f15b0 --label e28490 --workdir /github/workspace --rm -e PAT -e INPUT_SOURCE_REPO -e INPUT_SOURCE_BRANCH -e INPUT_DESTINATION_BRANCH -e INPUT_GITHUB_TOKEN -e INPUT_SYNC_TAGS -e GITHUB_TOKEN -e SYNC_TAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/doge-template/doge-template":"/github/workspace" ghcr.io/repo-sync/github-sync:v2.3.0  "https://github.com/zero205/JD_tencent_scf.git" "scf2:main"
UPSTREAM_REPO=https://github.com/zero205/JD_tencent_scf.git
BRANCHES=scf2:main
Resetting origin to: ***github.com/pengpengdaye/doge-template
Adding tmp_upstream https://github.com/zero205/JD_tencent_scf.git
Fetching tmp_upstream
origin	***github.com/pengpengdaye/doge-template (fetch)
origin	***github.com/pengpengdaye/doge-template (push)
tmp_upstream	https://github.com/zero205/JD_tencent_scf.git (fetch)
tmp_upstream	https://github.com/zero205/JD_tencent_scf.git (push)
Pushing changings from tmp_upstream to origin
remote: Permission to pengpengdaye/doge-template.git denied to pengpengdaye.
fatal: unable to access 'https://github.com/pengpengdaye/doge-template/': The requested URL returned error: 403

**Comment by Ca11back** [comment]
麻烦看教程,PAT不对
