### ISSUE TITLE
青龙或云函数无法jd签到

### ISSUE THREAD

**Issue by slmepipi** [zero205/JD_tencent_scf#274]
![image](https://user-images.githubusercontent.com/29816608/142396041-17428d6f-0145-4551-9f71-995a0f9711ca.png)
![image](https://user-images.githubusercontent.com/29816608/142396066-43bd2415-f23c-40f6-b87b-d7eced84abac.png)

**Comment by slmepipi** [comment]
![image](https://user-images.githubusercontent.com/29816608/142396471-d1f8c6c9-4c47-49ec-8cf0-aed9056d2d51.png)

**Comment by Ca11back** [comment]
?看下群内依赖安装
