### ISSUE TITLE
好像汪汪乐园出问题了

### ISSUE THREAD

**Issue by fantasyjqc** [zero205/JD_tencent_scf#276]
不知道是不是我ip被黑了，还是脚本问题，其他脚本是正常的，例如做汪汪乐园任务和助力的，只有合成的挂了

![image](https://user-images.githubusercontent.com/4988150/142577423-b3b8f6d7-daa7-42f2-8823-66e6b8bf4fdf.png)

**Comment by Ca11back** [comment]
应该是,没有换IP尝试?

**Comment by fantasyjqc001** [comment]
更换了IP，还是报同样的错误
