### ISSUE TITLE
企业微信文本过长问题

### ISSUE THREAD

**Issue by zronghui01** [zero205/JD_tencent_scf#278]
sendNotify:616: text.content exceed max length 5120. Invalid input invalid Request Parameter, hint: [1637397206_195_a8845607a1b49e22cba79fa222720e57], from ip: 1.12.238.65, more info at https://open.work.weixin.qq.com/devtool/query?e=40058

资产变动的时候太长了，导致发送微信通知失败
能不能设置每 3 个账号发送一次通知？

**Comment by Ca11back** [comment]
自己读下注释,去看下说明
