### ISSUE TITLE
 0点总是运行大于64报错

### ISSUE THREAD

**Issue by heimawsw** [zero205/JD_tencent_scf#285]
0点总是运行大于64的原因经过这几天我感觉是因为0点前，也就是23点59分的时候有一个定时。然后这个一分钟内运行不完，0点再启动0点的，就64MB崩了。

**Comment by Ca11back** [comment]
并无关系,前几天0点的已经挪了很多出去,而且签到也改了默认从参数
解决方法可readme什么的都有,有意见群内反馈就行
