### ISSUE TITLE
签到领现金  "Timeout awaiting 'request' for 30000ms"

### ISSUE THREAD

**Issue by sgzman** [zero205/JD_tencent_scf#289]
"Timeout awaiting 'request' for 30000ms"
签到领现金 API请求失败，请检查网路重试

ssh 腾讯云 ping api.m.jd.com  可以通

**Comment by Ca11back** [comment]
网络问题

**Comment by sgzman** [comment]
> 网络问题

![image](https://user-images.githubusercontent.com/31655098/143545564-adc3c937-054a-4ff3-851c-a7fa429bddd0.png)

也能ping通，难道是黑号了？
