### ISSUE TITLE
可否每个活动的任务日志里面都显示自己帐号的shareCode，以处理内部互助

### ISSUE THREAD

**Issue by FreeForQuantum** [zero205/JD_tencent_scf#302]
可否每个活动的任务日志里面都显示自己帐号的shareCode，以处理内部互助

**Comment by FreeForQuantum** [comment]
京东摇钱树助力等

**Comment by FreeForQuantum** [comment]
未在日志中提供助力值：
京东摇钱树助力

没有给出环境变量名称：
5G超级盲盒
惊喜牧场
金融养猪
QQ星系牧场
柠檬推一推

**Comment by Ca11back** [comment]
除了最后一个,都是默认内部互助,建议现在群内了解,感谢

**Comment by FreeForQuantum** [comment]
你好，我是国内用户。目前可能还没办法使用TG。想说有没有其他途径可以加入内部互助

**Comment by Ca11back** [comment]
默认,默认,默认
只要你不瞎搞,默认就是内部互助
如果感兴趣,可以直接看代码

**Comment by FreeForQuantum** [comment]
OK,感谢答复。
