### ISSUE TITLE
提示缺少jdcookie.js

### ISSUE THREAD

**Issue by BA7JCM** [zero205/JD_tencent_scf#305]
青龙面板直接用readme里面的命令拉取的话就会提示缺少./jdCookie.js，得自己手动往文件夹里面丢这个文件，不知道什么原因
![image](https://user-images.githubusercontent.com/79561519/146424208-b56d1a75-82ca-45b6-9c65-f22fd32be458.png)

**Comment by Ca11back** [comment]
正常应该并不会,这是完整仓库,是不是自己做了什么设置?

**Comment by BA7JCM** [comment]
> 正常应该并不会,这是完整仓库,是不是自己做了什么设置?

不知道，我啥也没动，就直接复制粘贴的readme里的命令，github仓库里我看了确实有这个文件，但用这个命令就拉不到那个文件
