### ISSUE TITLE
调整代码同步上云的频率

### ISSUE THREAD

**Issue by Andy-Chuck** [zero205/JD_tencent_scf#307]
Private仓库的Actions存在运行时长限制，如果按一天运行3次，一次运行2分钟计算，会导致Actions使用超限。
已尝试修改了main/.github/workflows/deploy.yml文件，停止了Random Cron，但每次都会被Sync覆盖。
请问是否可以调整代码同步上云的频率，或者把相关密钥存入Secrets中，变更仓库为Public？

**Comment by Ca11back** [comment]
ac私库限制普通帐号为2K分钟,每天部署6次都够
以前是public,但是没有private方便
需要自己调整的话,不Sycn就完事了.部署脚本不经常更新

**Comment by Andy-Chuck** [comment]
好的，谢谢
