### ISSUE TITLE
见缝插针

### ISSUE THREAD

**Issue by T3rdW** [zero205/JD_tencent_scf#308]
脚本名: jd_jfcz.js
![image](https://user-images.githubusercontent.com/14792476/146644853-a6f5fc42-fbbf-4977-aa21-676e7dbe4e1b.png)
建议加个判断,风控用户,直接跳入下一个账号,否则无限死循环

**Comment by Ca11back** [comment]
7d87e0487ed272ba60f816cb527f942a4749e90d
