### ISSUE TITLE
NOT_RUN 环境变量设置的是脚本的文件名还是显示在面板上的名字

### ISSUE THREAD

**Issue by zhxingway** [zero205/JD_tencent_scf#319]
![image](https://user-images.githubusercontent.com/43720357/148896247-039baf78-c50f-4781-a8ed-0c24b4e29ae0.png)

![image](https://user-images.githubusercontent.com/43720357/148896317-f67129a5-31bf-41fa-837f-63a0978b4eee.png)

如上图，我要禁止东东萌宠运行，请问以下哪个答案是正确答案啊？
A. 东东萌宠
B.  zero205_JD_tencent_scf_main/jd_pet.js
C.  jd_pet.js
D.  jd_pet

**Comment by 717009629** [comment]
你试下不就知道了

**Comment by zhxingway** [comment]
> 



>

**Comment by zhxingway** [comment]
> 你试下不就知道了

还有个问题就是，我手动运行受这个变量的影响吗？

**Comment by 717009629** [comment]
这个也可以试下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 下午3:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zero205/JD_tencent_scf] NOT_RUN 环境变量设置的是脚本的文件名还是显示在面板上的名字 (Issue #319)





  
你试下不就知道了
  
还有个问题就是，我手动运行受这个变量的影响吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhxingway** [comment]
> 

答案B

手动运行不受此变量影响

**Comment by Ca11back** [comment]
云函数专用,当初忘了注明....
