### ISSUE TITLE
浏览器扩展程序获取cookie，多账号怎么获取？

### ISSUE THREAD

**Issue by binge8** [zero205/JD_tencent_scf#323]
如题，确实简单好用，但是多账号怎么依次获取呢？不开无痕模式的话，退出前面的账号才能登陆下一个，可是退出前面的账号cookie也就失效了，用无痕模式吧，这个扩展插件好像不能用

**Comment by Ca11back** [comment]
无痕模式用插件属于浏览器操作范畴,自己在浏览器开启一下

**Comment by binge8** [comment]
> 无痕模式用插件属于浏览器操作范畴,自己在浏览器开启一下

无痕模式这个开启了。可是又有个新问题。无痕模式获取完上一个账号cookie后，关闭浏览器，重新打开一个无痕模式，再登陆下一个账号，点击显示cookie后，显示的还是上一个账号的cookie，这。。。。。。。
