### ISSUE TITLE
青龙脚本clone失败

### ISSUE THREAD

**Issue by summmer-is-hot** [zero205/JD_tencent_scf#324]
![image](https://user-images.githubusercontent.com/87792134/150099941-3906dd93-bd08-4e89-a202-fc9c120b9032.png)

**Comment by Ca11back** [comment]
可以尝试关闭青龙config中的ghproxy,注释GitrhubProxyURL

**Comment by Ca11back** [comment]
> 可以尝试关闭青龙config中的ghproxy,注释GitrhubProxyURL
好像是设置为""才能去掉?

**Comment by Ca11back** [comment]
config中的
GitrhubProxyURL设置为""空
如果有extrash,也要改

**Comment by Ca11back** [comment]
如果按上述教程,去掉加速后直连失败,可以等待晚上,估计加速会回复

**Comment by summmer-is-hot** [comment]
移除了proxy，直连也是失败呢~，明天看看情况吧~

**Comment by Ca11back** [comment]
> 移除了proxy，直连也是失败呢~，明天看看情况吧~

加速的话晚上应该能好,等下吧

**Comment by Ca11back** [comment]
青龙拉库失败的,可以尝试关闭青龙config中的ghproxy
将GithubProxyUrl设置为空
如果有extra的话,也要改一下

如果去掉后直连无法链接,等下就行,估计晚上能恢复
临时解决方法:
GithubProxyUrl设置为:
https://pd.zwc365.com/ 或
https://pd.zwc365.com/cfworker/

或更换拉库命令为:
ql repo https://github.com.cnpmjs.org/zero205/JD_tencent_scf.git "jd_|jx_|getJDCookie" "backUp|icon" "^jd[^_]|USER|sendNotify|sign_graphics_validate|JDJR|JDSign" "main"

ghproxy估计会在晚些时候回复,少安勿躁

云函数不受影响

**Comment by Ca11back** [comment]
ghproxy已经恢复了
https://ghproxy.com/
方便的话可以捐助支持一下
