### ISSUE TITLE
东东工厂跑完任务不全

### ISSUE THREAD

**Issue by xiqial** [zero205/JD_tencent_scf#326]
如题，大佬有时间修复一下啊

**Comment by shufflewzc** [comment]
@xiqial 好

**Comment by Ca11back** [comment]
> 如题，大佬有时间修复一下啊
反馈请代日志走流程,谢谢
工厂意义不大

**Comment by xiqial** [comment]
> > 如题，大佬有修复啊
> > 反馈请代日志走一下流程，谢谢
> > 工厂意义不大

还行啊，上次换了个好像298的电饭煲

**Comment by xiqial** [comment]
看大佬能否修复下，就漏了浏览5秒那个任务

**Comment by Ca11back** [comment]
> 看大佬能否修复下，就漏了浏览5秒那个任务

没啥意义的,哪怕全不能用了 (~_,~ ) ,可以自己玩玩看看
