### ISSUE TITLE
浏览器插件获取cookie的问题

### ISSUE THREAD

**Issue by binge8** [zero205/JD_tencent_scf#327]
无痕模式获取完上一个账号cookie后，关闭浏览器，重新打开一个无痕模式，再登陆下一个账号，点击显示cookie后，显示的还是上一个账号的cookie，这。。。。。。。

**Comment by ndog** [comment]
有这么麻烦吗？我就是正常登录，然后直接浏览器设置里清理cookie就行了。

**Comment by binge8** [comment]
好的，谢谢，如果方便的话，在插件上增加一个清理cookie按钮，就更完美了
