### ISSUE TITLE
Github的Actions里workflows越来越多

### ISSUE THREAD

**Issue by njuws** [zero205/JD_tencent_scf#328]
在Gtihub建了自己的私库，运行了一个多月，发现Actions里正在运行的workflows已经好几百个了，Github又没有批量删workflows的功能，所以有没有办法设置workflows的到期时间或者自动删除workflows？

**Comment by Ca11back** [comment]
是日志好几百了个,会自动删除,可以自己调整,github问题可以尝试上网搜索解决
