### ISSUE TITLE
腾讯云函数更新操作失败

### ISSUE THREAD

**Issue by kunnndo** [zero205/JD_tencent_scf#329]
如题，这几天都是如此：
2022-01-25 23:55:57 函数更新操作失败。您仍可以调用函数，此时调用的是更新之前的函数。
未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

**Comment by Ca11back** [comment]
请阅读FAQ:
https://github.com/zero205/JD_tencent_scf/tree/scf2

> Github部署日志:未找到函数执行入口文件
> 云函数面板删除函数,更改函数名字TENCENT_FUNCTION_NAME(Secret)(就是随便换个函数名字),重新运行action部署.
