### ISSUE TITLE
还是不行

### ISSUE THREAD

**Issue by kunnndo** [zero205/JD_tencent_scf#330]
昨天我发了   云函数Github部署日志报错:未找到函数执行入口文件

按照教程云函数面板删除函数,更改函数名字TENCENT_FUNCTION_NAME(Secret)(就是随便换个函数名字),重新运行action部署.
 
重新试过好几次都不行，脚本无法执行，我尝试单独运行某个脚本却显示：
当前是 异 步执行
异步执行不支持params参数!

**Comment by Ca11back** [comment]
无法理解报错,请清晰描述问题

**Comment by kunnndo** [comment]
你也还没睡啊，辛苦了

就是我重新部署后，脚本还是无法执行，例如我尝试运行 jd_m_sign这个脚本，云函数执行日志显示
参数触发方式(不读取配置文件),触发参数: jd_m_sign
当前是 异 步执行
异步执行不支持params参数!

**Comment by Ca11back** [comment]
你好像在群里问过了,群里也回答过了
日志没看出来有任何异常
如果说的是脚本应该是只跑了一点,单独测试脚本的时候偶尔会有这个毛病,暂时无法解决
自己观察整点触发器日志是否正常

**Comment by Ca11back** [comment]
如果问的是
>  异步执行不支持params参数!
这只是一行普通输出

**Comment by Ca11back** [comment]
@Ca11back Yu

**Comment by kunnndo** [comment]
我没有在群里问过，应该是别人也出现同样的问题了。
从今天零点开始，任何脚本都没有执行成功，一个京豆没有拿到。
四点时候的执行日志：
START RequestId:fda45df2-71d4-4b7c-898a-0d9be141727d
云函数帮助:自己私库下readme文件,或者访问:https://github.com/zero205/JD_tencent_scf/tree/scf2
hourly config触发,当前: 4
/var/user/config.json 存在
/var/user/config_diy.json 不存在或解析异常
params: {
  global: { timeout: 10 },
  jd_try: { timeout: 30 },
  jd_speed_sign: { timeout: 55 }
}
index:157: index:157: index:73: jd_redrain:数字参数触发
index:157: index:157: index:79: jd_dreamFactory:列表参数触发
index:157: index:157: index:73: jd_joy_feedPets:数字参数触发
index:157: index:157: index:79: jd_jxmc:列表参数触发
index:157: index:157: index:79: jd_mohe:列表参数触发
index:157: index:157: index:79: jd_try:列表参数触发
当前是 异 步执行
异步执行不支持params参数!
index:168: run script:jd_redrain
jd_redrain:315: 
🔔整点京豆雨, 开始!
jd_redrain:315: 
甘露殿【https://t.me/jdredrain】提醒你:本地红包雨配置获取错误，尝试从远程读取配置
index:168: run script:jd_dreamFactory
jd_dreamFactory:1732: 
🔔京喜工厂, 开始!
jd_dreamFactory:69: 【注意】本脚本默认会给助力池进行助力！
如需加入助力池请添加TG群：https://t.me/jd_zero_205
如不加入助力池互助，可添加变量名称：JD_JOIN_ZLC，变量值：false
jd_dreamFactory:1428: 开始获取京喜工厂配置文件
jd_dreamFactory:1431: 共1个京东账号
jd_dreamFactory:1444: 您提供了2个账号的京喜工厂助力码
index:168: run script:jd_joy_feedPets
jd_joy_feedPets:256: 
🔔宠汪汪🐕喂食, 开始!
index:168: run script:jd_jxmc
jd_jxmc:1163: 
🔔京喜牧场, 开始!
index:168: run script:jd_mohe
jd_mohe:537: 
🔔5G超级盲盒, 开始!
jd_mohe:46: 5G超级盲盒，可抽奖获得京豆，建议在凌晨0点时运行脚本，白天抽奖基本没有京豆，3小时运行一次收集热力值
活动地址: https://blindbox5g.jd.com
活动时间：2021-8-2到2021-10-29
更新时间：2021-8-8 19:00
index:168: run script:jd_try
jd_try:1192: 
🔔京东试用, 开始!
jd_try:156: X1a0He留：遇到问题请把脚本内的注释看一遍再来问，谢谢
jd_try:157: X1a0He留：遇到问题请把脚本内的注释看一遍再来问，谢谢
jd_try:158: X1a0He留：遇到问题请把脚本内的注释看一遍再来问，谢谢
Response RequestId:fda45df2-71d4-4b7c-898a-0d9be141727d RetMsg:null
END RequestId:fda45df2-71d4-4b7c-898a-0d9be141727d
Report RequestId:fda45df2-71d4-4b7c-898a-0d9be141727d Duration:58ms Memory:64MB MemUsage:29.423225MB



我就是不明白为什么会这样，谢谢。

**Comment by Ca11back** [comment]
带这种日志请入群提问,已理解问题,尝试解决,请入群反馈

**Comment by kunnndo** [comment]
好吧，我现在去群问问，谢谢
