### ISSUE TITLE
部署不上  setting里边secrets变成两类了

### ISSUE THREAD

**Issue by AaronFXLCXC** [zero205/JD_tencent_scf#331]

**Comment by AaronFXLCXC** [comment]
两个都填了还是没反应  刚从云函数删了就部署不进去了。。。

**Comment by Ca11back** [comment]
请清晰描述问题

**Comment by AaronFXLCXC** [comment]
就是我前几天脚本不好使了 我给删了  今天又去从头部署了一遍  我action里运行完了部署到云 显示成功  但是云函数里啥都没有  而且github的setting也改版了  看不明白  那个secret分成了action和dependabot  咱也不知道到底填那个  俩都填了还是部署不到云上

**Comment by Ca11back** [comment]
群里问过是吧
请提供action日志,最好去群内
大概率自己弄错地区了

**Comment by AaronFXLCXC** [comment]
谢谢大佬
