### ISSUE TITLE
telegram请求超时

### ISSUE THREAD

**Issue by NoodlesGentleman** [zero205/JD_tencent_scf#335]
![image](https://user-images.githubusercontent.com/32062284/152370528-1d8bd8ae-1807-4785-8241-8b73a247afd6.png)

**Comment by Ca11back** [comment]
https://github.com/zero205/JD_tencent_scf/tree/scf2#tg%E6%8E%A8%E9%80%81%E8%AF%B7%E6%B1%82%E9%94%99%E8%AF%AF
