### ISSUE TITLE
jd_cfd_loop.js TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by BuleWhale** [zero205/JD_tencent_scf#336]
这是nodejs版本问题吗，我的版本是v16.13.1
![image](https://user-images.githubusercontent.com/35369979/152481009-c0fa084f-55c9-4250-93f9-f427abb11b1e.png)

**Comment by Ca11back** [comment]
劳烦群内反馈,大概率自己帐号问题
