### ISSUE TITLE
这两天任务更新一直报错，提示缺少.ql文件，

### ISSUE THREAD

**Issue by daihao0903** [zero205/JD_tencent_scf#351]
![image](https://user-images.githubusercontent.com/14958793/158046024-de0ef59f-11c3-4700-a875-2461af965c65.png)

**Comment by redbeanzzZ** [comment]
同样的情况

**Comment by fjqken** [comment]
同样情况

**Comment by yangyangxing** [comment]
我也是有解决方法么，npm各种方法都试了

**Comment by fjqken** [comment]
> 我也是有解决方法么，npm各种方法都试了

我部署了新的青龙面板，可以解决该问题
