### ISSUE TITLE
请问云函数如何自己关闭某些脚本的运行，比如京东试用，如何自己关闭呢

### ISSUE THREAD

**Issue by lendcc** [zero205/JD_tencent_scf#39]

**Comment by zero205** [comment]
![image](https://user-images.githubusercontent.com/26343559/121640031-fbfa9600-cabf-11eb-84ce-e15aa55aaef0.png)
删除一个原来的触发器，重新创建。附加信息出填需要运行的脚本
重新部署的话会覆盖，需要再次重复操作

**Comment by lendcc** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/26343559/121640031-fbfa9600-cabf-11eb-84ce-e15aa55aaef0.png)
> 删除一个原来的触发器，重新创建。附加信息出填需要运行的脚本
> 重新部署的话会覆盖，需要再次重复操作

这样确实可以，不过这样非常麻烦， 是否更一劳永逸的方法呢？

**Comment by CACAVOK** [comment]
> ![image](https://user-images.githubusercontent.com/26343559/121640031-fbfa9600-cabf-11eb-84ce-e15aa55aaef0.png)
> 删除一个原来的触发器，重新创建。附加信息出填需要运行的脚本
> 重新部署的话会覆盖，需要再次重复操作

请问是这边项目有更新操作才触发重新部署操作还是定时每天重新部署呢？就是我新建触发器的有效时间有多长呢老哥

**Comment by Cyj97** [comment]
修改触发器或者serverless.yml编辑=》删除&jd_try =》部署
