### ISSUE TITLE
同步到腾讯云函数之后，触发器未能自动创建

### ISSUE THREAD

**Issue by etmty** [zero205/JD_tencent_scf#4]
好像是触发器的name太长了，超过60字节了？

**Comment by zero205** [comment]
已经修改了，还存在这个问题吗？

**Comment by etmty** [comment]
2部署到腾讯云函数(主云函数)
2部署到腾讯云函数(主云函数) #33: Manually run by etmty
 11 minutes ago
 2m 38s
1获取最新脚本
1获取最新脚本 #15: Manually run by etmty
 13 minutes ago
 1m 6s

——————————————————————————
刚试了下，部署到腾讯云后，触发器仍然是空的哈
