### ISSUE TITLE
京喜财富岛的云函数部署填错了，导致长度过长，定时触发器同步不过去

### ISSUE THREAD

**Issue by qiubeiliana** [zero205/JD_tencent_scf#40]
![image](https://user-images.githubusercontent.com/85653270/121628823-951fb180-caac-11eb-893d-96afcf6b893a.png)

https://github.com/zero205/JD_tencent_scf/blob/main/.github/workflows/deploy_tencent_scf.yml

路径如图

**Comment by zero205** [comment]
已删除

**Comment by qiubeiliana** [comment]
感谢
