### ISSUE TITLE
同步云函数替换变量时报错了

### ISSUE THREAD

**Issue by zhangdaren2490** [zero205/JD_tencent_scf#43]
Run if [ $***_COOKIE ]; then sed -i "/variables/a\      ***_COOKIE: $***_COOKIE" serverless.yml; fi;
sed: -e expression #1, char 33: extra characters after command
Error: Process completed with exit code 1.

在同步云函数 时，报错如上，请大佬帮忙，感谢

**Comment by zero205** [comment]
你填的京东ck是不是用回车换行了？

**Comment by zhangdaren2490** [comment]
用的&符号啊

**Comment by zhangdaren2490** [comment]
知道了，原来有个cookie的格式没写对。
