### ISSUE TITLE
大佬，云函数运行内存改为64M会不会不够用呀？

### ISSUE THREAD

**Issue by qxy0789** [zero205/JD_tencent_scf#56]
我看了下我部署的腾迅云函数运行内存的监控，峰值达到100M，改成64M会受影响吗？

**Comment by zero205** [comment]
群了有人说改成64，你是挂了几个号？我现在超额欠费了看不了日志，不行的话就改会128吧

**Comment by 3136083906** [comment]
> 群了有人说改成64，你是挂了几个号？我现在超额欠费了看不了日志，不行的话就改会128吧

能不能减少通知频率，pluspush现在每天有200条限制了

**Comment by Mario0o** [comment]
一天超不了200条啊

**Comment by tangclQaQ** [comment]
![123](https://user-images.githubusercontent.com/46365772/122528719-3c718b00-d04f-11eb-8bb6-eef46f2da90d.png)
7天的内存监控，偶尔会超过64，感觉问题不是很大，我是挂的一个号

**Comment by jkluio78** [comment]
赞成改成128M，这几天的运行内存好几次都是逼近64M了，后面再加脚本可能会超吧

**Comment by zero205** [comment]
因为现在开启了异步执行，解决了运行900秒的限制，考虑到多账号的原因，运行时间会比较长，资源使用快。每月40万GBs的免费额度担心不够用，所以先尝试降价运行内存。后面反馈的人多的话就改回128M吧

**Comment by jkluio78** [comment]
> 因为现在开启了异步执行，解决了运行900秒的限制，考虑到多账号的原因，运行时间会比较长，资源使用快。每月40万GBs的免费额度担心不够用，所以先尝试降低运行内存。后面反馈的人多的话就改回128M吧

作者要不考虑加个配置内存的环境变量，默认数值（不填）是64，需要更大的就填128、256等等，这样可以吗

**Comment by zero205** [comment]
> > 因为现在开启了异步执行，解决了运行900秒的限制，考虑到多账号的原因，运行时间会比较长，资源使用快。每月40万GBs的免费额度担心不够用，所以先尝试降低运行内存。后面反馈的人多的话就改回128M吧
> 
> 作者要不考虑加个配置内存的环境变量，默认数值（不填）是64，需要更大的就填128、256等等，这样可以吗

不错的建议，等下周我尝试添加一下试试

**Comment by jkluio78** [comment]
> > > 因为现在开启了异步执行，解决了运行900秒的限制，考虑到多账号的原因，运行时间会比较长，资源使用快。每月40万GBs的免费额度担心不够用，所以先尝试降低运行内存。后面反馈的人多的话就改回128M吧
> > 
> > 
> > 作者要不考虑加个配置内存的环境变量，默认数值（不填）是64，需要更大的就填128、256等等，这样可以吗
> 
> 不错的建议，等下周我尝试添加一下试试

假设环境变量是`TENCENT_MemorySize`，我的想法是对输入的环境变量再做下修正，因为128已经够用了，所以输入超过64的值就设定为128，小于等于64或者没有输入就是64

`const MemorySize=process.env.TENCENT_MemorySize?(Number(process.env.TENCENT_MemorySize)>64?128:64):64;`

![image](https://user-images.githubusercontent.com/74967641/122644110-20044a00-d146-11eb-9114-e86db14bbfb2.png)

然后再修改下传入的值，应该就可以了吧

`MemorySize: MemorySize,`

![image](https://user-images.githubusercontent.com/74967641/122644136-4fb35200-d146-11eb-8992-79dcac80da13.png)

**Comment by zero205** [comment]
> > > > 因为现在开启了异步执行，解决了运行900秒的限制，考虑到多账号的原因，运行时间会比较长，资源使用快。每月40万GBs的免费额度担心不够用，所以先尝试降低运行内存。后面反馈的人多的话就改回128M吧
> > > 
> > > 
> > > 作者要不考虑加个配置内存的环境变量，默认数值（不填）是64，需要更大的就填128、256等等，这样可以吗
> > 
> > 
> > 不错的建议，等下周我尝试添加一下试试
> 
> 假设环境变量是`TENCENT_MemorySize`，我的想法是对输入的环境变量再做下修正，因为128已经够用了，所以输入超过64的值就设定为128，小于等于64或者没有输入就是64
> 
> `const MemorySize=process.env.TENCENT_MemorySize?(Number(process.env.TENCENT_MemorySize)>64?128:64):64;`
> 
> ![image](https://user-images.githubusercontent.com/74967641/122644110-20044a00-d146-11eb-9114-e86db14bbfb2.png)
> 
> 然后再修改下传入的值，应该就可以了吧
> 
> `MemorySize: MemorySize,`
> 
> ![image](https://user-images.githubusercontent.com/74967641/122644136-4fb35200-d146-11eb-8992-79dcac80da13.png)

你测试完可以的话欢迎PR过来我合并一下，谢谢^_^

**Comment by jkluio78** [comment]
> > > 因为现在开启了异步执行，解决了运行900秒的限制，考虑到多账号的原因，运行时间会比较长，资源使用快。每月40万GBs的免费额度担心不够用，所以先尝试降低运行内存。后面反馈的人多的话就改回128M吧
> > 
> > 
> > 作者要不考虑加个配置内存的环境变量，默认数值（不填）是64，需要更大的就填128、256等等，这样可以吗
> 
> 不错的建议，等下周我尝试添加一下试试

用账号名为`Mking`的账户发起了PR
