### ISSUE TITLE
大佬京喜农场通知变量是什么？

### ISSUE THREAD

**Issue by qiubeiliana** [zero205/JD_tencent_scf#58]
大佬京喜农场通知变量是什么？现在默认不通知了，种子死了也不知道，熟了也不知道，因为这个周期比较短，希望还是加上通知好点。
找了半天没发现控制通知的变量

**Comment by zero205** [comment]
京喜农场默认是开启通知的，只在成熟的时候会发送通知

**Comment by zero205** [comment]
环境变量JXNC_NOTIFY_LEVEL
可以控制通知等级
通知级别填对应数字即可：0=只通知成熟；1=本次获得水滴>0；2=任务执行；3=任务执行+未种植种子;

**Comment by qiubeiliana** [comment]
感谢！
