### ISSUE TITLE
同步到云函数因line 83多了条重复代码导致失败

### ISSUE THREAD

**Issue by YEJT66** [zero205/JD_tencent_scf#59]
![image](https://user-images.githubusercontent.com/85723270/122662735-e542f600-d1c7-11eb-9ef8-fdf1cacbf9fb.png)
删除后正常

**Comment by zero205** [comment]
感谢提醒，已修复

**Comment by phb8960296** [comment]
同步后   触发管理   没有创建

**Comment by phb8960296** [comment]
region: ap-guangzhou # 函数所在区域  在其他地区怎么办
