### ISSUE TITLE
云函数好像扣费了

### ISSUE THREAD

**Issue by SalayDay** [zero205/JD_tencent_scf#63]
同样跑了几个月的项目，今天提示我这个月欠费了  前面都没有这种情况   是什么原因呢

**Comment by SalayDay** [comment]
acton部署到云函数之后index是本地运行的吗

**Comment by phb8960296** [comment]
内存用64  这样用的时间长点

**Comment by tangclQaQ** [comment]
一直都是要付费的，主要是访问外网流量要钱，之前没让你付费，是因为第一次用云函数会送10块红包，这个脚本费流量少，这个10元红包能用很久

**Comment by SalayDay** [comment]
懂了   就是后面都是要钱的对吧
