### ISSUE TITLE
同步后,云函数被删除了,提示部署失败

### ISSUE THREAD

**Issue by w-jx** [zero205/JD_tencent_scf#65]
![image](https://user-images.githubusercontent.com/59555887/122842158-594bde00-d32f-11eb-9458-07deaa1b4615.png)

**Comment by belleetoile** [comment]
同样的情况

**Comment by qiubeiliana** [comment]
同样的情况

**Comment by llyy390** [comment]
一样的情况

**Comment by MINGX2021** [comment]
俺也一样
Error: encentCloudSDKHttpException [Error]: Request Entity Too Large

**Comment by llyy390** [comment]
和你一样的提示 Error: encentCloudSDKHttpException [Error]: Request Entity Too Large

**Comment by zero205** [comment]
已紧急修复，同步最新脚本重新布署即可

**Comment by llyy390** [comment]
谢谢大神
