### ISSUE TITLE
定时当中没有多合一签到吗？

### ISSUE THREAD

**Issue by 895450603** [zero205/JD_tencent_scf#71]
大佬，定时当中没有jd_bean_sign.js和jd_jxmc.js，暂时只发现这两个，是这样嘛？

**Comment by wysunrise2** [comment]
> 大佬，定时当中没有jd_bean_sign.js和jd_jxmc.js，暂时只发现这两个，是这样嘛？

都有，你可以在serverless.yml源文件里找到它们的定时触发器的设定。部署后，云函数里也有，签到是0 30 9 * * * *，京喜牧场是0 30 8,12,19,6-23/6 * * * *

**Comment by 895450603** [comment]
> > 大佬，定时当中没有jd_bean_sign.js和jd_jxmc.js，暂时只发现这两个，是这样嘛？
> 
> 都有，你可以在serverless.yml源文件里找到它们的定时触发器的设定。部署后，云函数里也有，签到是0 30 9 * * * *，京喜牧场是0 30 8,12,19,6-23/6 * * * *

不好意思，请教下，因为我用的是隔壁的面板，不知道这个定时的文件在哪个位置？谢谢🙏

**Comment by wysunrise2** [comment]
> > > 大佬，定时当中没有jd_bean_sign.js和jd_jxmc.js，暂时只发现这两个，是这样嘛？
> > 
> > 
> > 都有，你可以在serverless.yml源文件里找到它们的定时触发器的设定。部署后，云函数里也有，签到是0 30 9 * * * *，京喜牧场是0 30 8,12,19,6-23/6 * * * *
> 
> 不好意思，请教下，因为我用的是隔壁的面板，不知道这个定时的文件在哪个位置？谢谢🙏

![S10623-22574631](https://user-images.githubusercontent.com/82127901/123119917-7f2fca80-d476-11eb-9afe-696db6912827.jpg)
就这个项目根目录

**Comment by 895450603** [comment]
> > > > 大佬，定时当中没有jd_bean_sign.js和jd_jxmc.js，暂时只发现这两个，是这样嘛？
> > > 
> > > 
> > > 都有，你可以在serverless.yml源文件里找到它们的定时触发器的设定。部署后，云函数里也有，签到是0 30 9 * * * *，京喜牧场是0 30 8,12,19,6-23/6 * * * *
> > 
> > 
> > 不好意思，请教下，因为我用的是隔壁的面板，不知道这个定时的文件在哪个位置？谢谢🙏
> 
> ![S10623-22574631](https://user-images.githubusercontent.com/82127901/123119917-7f2fca80-d476-11eb-9afe-696db6912827.jpg)
> 就这个项目根目录

这个我有看到，所以面板的定时参数配置也是读的这个文件吗？

**Comment by wysunrise2** [comment]
是，你可以深入研究一下action里起作用的deploy_tencent_scf.yml文件，部署云函数的action运行的时候，这个源文件里会调用serverless.yml的内容。
