### ISSUE TITLE
极速版签到运行中卡死的问题

### ISSUE THREAD

**Issue by hoogyuan** [zero205/JD_tencent_scf#72]
从21号部署好到24号均无法完整运行，都是到第二个账号运行中的时候卡死，手动再次运行脚本也是依然卡死，无法继续

==================脚本执行- 北京时间(UTC+8)：2021/6/21 上午11:41:44=====================

*****开始【京东账号2】*********

【65/85】浏览商品任务记录成功，等待20秒

**Comment by Ca11back** [comment]
应该已经修复
