### ISSUE TITLE
财富岛脚本速度更改

### ISSUE THREAD

**Issue by Tsukasa007** [zero205/JD_tencent_scf#74]
jd_cfdtx.js 
ddwMinPaperMoney=100000
改成
ddwMinPaperMoney=150000

**Comment by mingrenbufanganpi** [comment]
你在哪跑的脚本？云函数里面能跑成功吗？

**Comment by HenryTSZ** [comment]
@Tsukasa007 请问财富岛的 token 只能通过手动提现成功后获取吗? 现在手动根本抢不过脚本, 完全没办法获取. 通过别的接口获取的 token 提示 提现信息不一致
