### ISSUE TITLE
小白们如果看issues，来看我一眼，我不是不给仓库主助力，但是你这样明着偷不好，交代一下吧

### ISSUE THREAD

**Issue by Tsukasa007** [zero205/JD_tencent_scf#78]
小白们如果看issues，来看我一眼，我不是不给仓库主助力，你这样明着偷不好，交代一下吧
env变量提取都注释了
懂代码的看一下jd_dyj.js的提交日志就懂了，我也没有否认仓库的作用，只是偷偷摸摸让小白蒙在鼓里，确实影响不好！
别删我哦！

**Comment by zero205** [comment]
大赢家的变量代码process在elecV2P无法运行，测试脚本的时候是用elecV2P测试的，所以我就直接注释了。这个活动因为需要很多人头，一般人都没这么多号（代挂除外），所以后面我也懒得适配elecV2P代码，就没管了。你要是觉得我偷你助力了，可以取消同步脚本，手动删除大赢家的运行任务。

**Comment by Tsukasa007** [comment]
说重点邀请码连续几天改自己的怎么回事
![image](https://user-images.githubusercontent.com/28201662/123508231-a7027680-d6a0-11eb-8f34-9d9f4507a15b.png)
