### ISSUE TITLE
jd_bean_sign.js不能运行

### ISSUE THREAD

**Issue by Benjamin-an** [zero205/JD_tencent_scf#81]
重新运行腾讯云函数，三个COOKIE，jd_bean_sign.js多合一签到 脚本无签到动作，并且京东无签到领京豆记录，微信server酱无推送，其他项目有推送。

**Comment by ziyingjie** [comment]
借个楼 想问一下 老哥 部署到腾讯云以后 仓库代码有更新的话 腾讯云那边也会跟随更新吗？(action执行？)

**Comment by Benjamin-an** [comment]
自动更新

**Comment by ziyingjie** [comment]
> 自动更新

嗯啊 看到了 action里面 多谢老哥

**Comment by ZeroCanBetter** [comment]
你好，请问腾讯云那边怎么自动更新啊？

**Comment by Benjamin-an** [comment]
> 你好，请问腾讯云怎么自动更新啊？

github自动覆盖腾讯云函数部署

**Comment by ZY9898** [comment]
淦，我现在也出现这种情况了，老铁怎么解决的？

**Comment by Ca11back** [comment]
bean_sign已更新
