### ISSUE TITLE
超时时间是否太长了

### ISSUE THREAD

**Issue by aligaduo689** [zero205/JD_tencent_scf#83]
超时时间是否太长了，86400秒，差不多24小时了，这样云函数扣费很多，感觉根本不需要那么多的

**Comment by zero205** [comment]
根据实际运行时间计算费用，不影响

**Comment by redmaple24** [comment]
大佬，为什么我每天就几十京豆，是有什么地方有错误吗，别人好像都几百的样子

**Comment by Ca11back** [comment]
> 根据实际运行时间计算费用，不影响

建议大佬缩短时间,缩短到够speed_sign运行完就行了,以防止未来有脚本出现死循环

**Comment by zero205** [comment]
> > 根据实际运行时间计算费用，不影响
> 
> 建议大佬缩短时间,缩短到够speed_sign运行完就行了,以防止未来有脚本出现死循环

因为考虑到有人号可能比较多，本来需要长时间运行的脚本因而需要更长的时间来满足

**Comment by zero205** [comment]
> > 根据实际运行时间计算费用，不影响
> 
> 建议大佬缩短时间,缩短到够speed_sign运行完就行了,以防止未来有脚本出现死循环

对了，jd_sign那个签到图形验证脚本能帮忙看一下需要怎么修改吗？貌似也运行不了😂😂

**Comment by Ca11back** [comment]
建议个人按需求缩短
