### ISSUE TITLE
京东试用无法运行，填了true一直显示日志拉取中

### ISSUE THREAD

**Issue by aligaduo689** [zero205/JD_tencent_scf#89]
![image](https://user-images.githubusercontent.com/86503257/124412873-0ee04d80-dd82-11eb-9412-841754c46f95.png)
京东试用无法运行，填了true一直显示日志拉取中

**Comment by zero205** [comment]
脚本原作者貌似原来就是没写日志输出，自己去试用里面看一下有没有在运行，我没跑这个脚本

**Comment by aligaduo689** [comment]
我去app看了，就是没跑。。昨天没更新还能跑的
