### ISSUE TITLE
夏日燃动help失效

### ISSUE THREAD

**Issue by D3ee** [zero205/JD_tencent_scf#97]
❗️燃动夏季_SH助力, 错误!
ReferenceError: Cannot access 'MovementFaker' before initialization

**Comment by D3ee** [comment]
第257行 const log = await getBody() 获取不到log

**Comment by zero205** [comment]
smiek2221的也不行啊..太难了...😢

**Comment by zero205** [comment]
我尝试修复了，你更新再试试

> ❗️燃动夏季_SH助力, 错误!
> ReferenceError: Cannot access 'MovementFaker' before initialization
